### PR TITLE
:recycle: refactor by unsafe code

### PR DESCRIPTION
**Pull request by frg2089**
This should provide a performance boost.

I added code to kill the pico_et_ft_bt_bridge.exe process and it may now be possible to run the module without removing pico_et_ft_bt_bridge.exe.
https://github.com/regzo2/PicoStreamingAssistantFTUDP/pull/3/commits/5bbb230729964bd7a889c6a3ccedc4e55cf3827f#diff-6e070d01f5c9e071f65b958859432bceaa872dfc097100051e5414f9641afcc9R56-R80

And I added code to check the Streaming Assistant process, so that the module will not time out when the process exists, but will simply fail when the process does not exist.
https://github.com/regzo2/PicoStreamingAssistantFTUDP/pull/3/commits/5bbb230729964bd7a889c6a3ccedc4e55cf3827f#diff-6e070d01f5c9e071f65b958859432bceaa872dfc097100051e5414f9641afcc9R34-R38

### CODE REVIEW

**Comment by regzo2** [comment]
Thanks! I will test it out and merge when I get back home

**Comment by frg2089** [comment]
After my testing, I can now switch between Streaming Assistant and VRCFT data streams at any time.

When running VRCFT, the module will kill the pico_et_ft_bt_bridge.exe process and listen to the port before it does, at which point VRChat will receive data from VRCFT.
After closing off VRCFT, pico_et_ft_bt_bridge.exe takes over the data again, and VRChat receives data from Streaming Assistant at that time.

**Comment by frg2089** [comment]
There seems to be a memory leak somewhere, I'll turn off this PR first.

**Comment by frg2089** [comment]
I didn’t find any memory leaks, but I fixed a busy wait.

**Comment by regzo2** [comment]
Seems to be very stable. I have a few people that have the Pico4Pro/Enterprise testing the changes out. All the changes seem to work pretty well so I'll go ahead and merge it! I am going to make a couple of changes regarding threading of the Update function (since it currently eats up a bunch of CPU cycles) but otherwise seems good to go.

**Comment by regzo2** [comment]
Looks like you already did the threading change! need to add a timeout so the Update thread doesn't get halted indefinitely.

**Pull request merged**
